//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenJs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int Id { get; set; }
        public string nomCours { get; set; }
        public string jours { get; set; }
        public string heureD { get; set; }
        public string heureF { get; set; }
        public int coef { get; set; }
        public int salleId { get; set; }
        public int matiereId { get; set; }
    
        public virtual Matiere Matiere { get; set; }
        public virtual Salle Salle { get; set; }
    }
}
