//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classe
    {
        public int Id { get; set; }
        public string code { get; set; }
        public string libelle { get; set; }
        public int fraisinscription { get; set; }
        public int mensualite { get; set; }
        public int filiere_id { get; set; }
    
        public virtual Filiere Filiere { get; set; }
    }
}
