//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string nomComplet { get; set; }
        public string tel { get; set; }
        public string adresse { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> profilId { get; set; }
    
        public virtual profil profil { get; set; }
    }
}
