//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionScolaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscription
    {
        public int Id { get; set; }
        public System.DateTime date { get; set; }
        public string anneeacademique { get; set; }
        public int etudiant_id { get; set; }
        public int classe_id { get; set; }
    
        public virtual Classe Classe { get; set; }
        public virtual Etudiant Etudiant { get; set; }
    }
}
