//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEcole
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PromoModule()
        {
            this.Seance = new HashSet<Seance>();
        }
    
        public int id { get; set; }
        public int idPromo { get; set; }
        public int idModule { get; set; }
        public int nbseance { get; set; }
        public int dureeseance { get; set; }
        public string jourseance { get; set; }
        public int notevalid { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Promo Promo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seance> Seance { get; set; }
    }
}
