
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace scolarite
{

using System;
    using System.Collections.Generic;
    
public partial class Etudiant
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Etudiant()
    {

        this.inscription = new HashSet<inscription>();

    }


    public int Id { get; set; }

    public string matricule { get; set; }

    public string prenom { get; set; }

    public string nom { get; set; }

    public System.DateTime datenaissance { get; set; }

    public string adresse { get; set; }

    public string email { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<inscription> inscription { get; set; }

}

}
