
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace scolarite
{

using System;
    using System.Collections.Generic;
    
public partial class utilisateur
{

    public int Id { get; set; }

    public string login { get; set; }

    public string password { get; set; }

    public string nomComplet { get; set; }

    public string profil { get; set; }

}

}
