//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenJava
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personne
    {
        public int Id { get; set; }
        public string code { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public int paysId { get; set; }
        public int adresseId { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        public virtual Pays Pays { get; set; }
    }
}
